services:
  periodictable.api:
    image: periodictable.api
    build:
      context: .
      dockerfile: src/PeriodicTable.Api/Dockerfile
    
  mongo-local:
    image: mongodb/mongodb-community-server:latest
    ports:
      - '27017:27017'
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=admin
      - MONGODB_INITDB_ROOT_PASSWORD=pass
    volumes:
      - ./mongo/seed:/docker-entrypoint-initdb.d
      
  